name = "lens-legend-test"
compatibility_date = "2025-11-21"
pages_build_output_dir = "./dist"

# 数据库绑定
[[d1_databases]]
binding = "lens_db"
database_name = "lens-db"
database_id = "ab2c38a7-1bbf-4308-b774-9b9f1d69111c"

# R2 存储绑定
[[r2_buckets]]
binding = "lens_storage"
bucket_name = "lens-storage"
